<Project>
  <UsingTask
    TaskName="Imlinka.Build.ImlinkaWeaveTask"
    AssemblyFile="$(MSBuildThisFileDirectory)..\tasks\netstandard2.0\Imlinka.Tasks.dll" />

  <Target
    Name="ImlinkaWeave"
    AfterTargets="CopyFilesToOutputDirectory"
    Condition="'$(ImlinkaWeavingEnabled)' != 'false'
      and '$(DesignTimeBuild)' != 'true'
      and '$(IsCrossTargetingBuild)' != 'true'
      and Exists('$(TargetPath)')">

    <ItemGroup>
      <ImlinkaWeaverAssembly Include="$(TargetPath)" />
      <ImlinkaWeaverAssembly
        Include="$(TargetDir)%(ReferencePath.Filename)%(ReferencePath.Extension)"
        Condition="'%(ReferencePath.Extension)' == '.dll'
          and '%(ReferencePath.ReferenceSourceTarget)' == 'ProjectReference'" />
      <ImlinkaWeaverSearchPath Include="$(TargetDir)" />
      <ImlinkaWeaverSearchPath Include="%(ReferencePath.RootDir)%(ReferencePath.Directory)" />
    </ItemGroup>

    <ImlinkaWeaveTask
      AssemblyPath="%(ImlinkaWeaverAssembly.Identity)"
      ImlinkaAssemblyPath="$(TargetDir)Imlinka.dll"
      References="@(ReferencePath)"
      SearchPaths="@(ImlinkaWeaverSearchPath)"
      IntermediateDirectory="$(IntermediateOutputPath)" />
  </Target>
</Project>
