<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <ProjectReference Include="..\Imlinka\Imlinka.csproj" />
    </ItemGroup>

    <UsingTask
        TaskName="Imlinka.Build.ImlinkaWeaveTask"
        AssemblyFile="..\Imlinka.Tasks\bin\$(Configuration)\netstandard2.0\Imlinka.Tasks.dll" />

    <Target
        Name="ImlinkaWeaveSample"
        AfterTargets="CopyFilesToOutputDirectory"
        Condition="'$(DesignTimeBuild)' != 'true' and Exists('$(TargetPath)')">
        <MSBuild
            Projects="..\Imlinka.Tasks\Imlinka.Tasks.csproj"
            Targets="Build"
            Properties="Configuration=$(Configuration)" />
        <ItemGroup>
            <ImlinkaSampleWeaverSearchPath Include="$(TargetDir)" />
            <ImlinkaSampleWeaverSearchPath Include="%(ReferencePath.RootDir)%(ReferencePath.Directory)" />
        </ItemGroup>
        <ImlinkaWeaveTask
            AssemblyPath="$(TargetPath)"
            References="@(ReferencePath)"
            SearchPaths="@(ImlinkaSampleWeaverSearchPath)"
            IntermediateDirectory="$(IntermediateOutputPath)" />
    </Target>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="OpenTelemetry.Exporter.Console" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Settings.Configuration" />
        <PackageReference Include="Serilog.Sinks.Console" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="serilog.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
